# Generated by Django 5.0.4 on 2024-04-10 17:55

from django.db import migrations

def filling_manual(apps, schema_editor):
    #Priority
    Priority = apps.get_model("project_catalog", "Priority")
    Priority.objects.create(name="Низкий", description="Низкий", color="grey")
    Priority.objects.create(name="Ниже среднего", description="Низкий", color="grey")
    Priority.objects.create(name="Средний", description="Низкий", color="grey")
    Priority.objects.create(name="Выше среднего", description="Низкий", color="grey")
    Priority.objects.create(name="Высокий", description="Низкий", color="grey")
    Priority.objects.create(name="Срочный", description="Низкий", color="grey")
    Priority.objects.create(name="Крайне срочный", description="Низкий", color="grey")

    #ProjectType
    ProjectType = apps.get_model("project_catalog", "ProjectType")
    ProjectType.objects.create(name="Веб приложение", description="Низкий", color="grey")
    ProjectType.objects.create(name="Система синхронизации", description="Низкий", color="grey")
    ProjectType.objects.create(name="Мобильное приложение", description="Низкий", color="grey")
    ProjectType.objects.create(name="Приложение для АРМ", description="Низкий", color="grey")
    ProjectType.objects.create(name="Информационный сайт", description="Низкий", color="grey")

    #TeamMemberRole
    TeamMemberRole = apps.get_model("project_catalog", "TeamMemberRole")
    TeamMemberRole.objects.create(name="Разработчик", description="Низкий", color="grey")
    TeamMemberRole.objects.create(name="Тестировщик", description="Низкий", color="grey")
    TeamMemberRole.objects.create(name="Писатель", description="Низкий", color="grey")
    TeamMemberRole.objects.create(name="Дизайнер", description="Низкий", color="grey")
    TeamMemberRole.objects.create(name="Аналитик", description="Низкий", color="grey")
    
    #ProjectComplexity
    ProjectComplexity = apps.get_model("project_catalog", "ProjectComplexity")
    ProjectComplexity.objects.create(name="Простой", description="Низкий", color="grey")
    ProjectComplexity.objects.create(name="Ниже среднего", description="Низкий", color="grey")
    ProjectComplexity.objects.create(name="Средний", description="Низкий", color="grey")
    ProjectComplexity.objects.create(name="Выше среднего", description="Низкий", color="grey")
    ProjectComplexity.objects.create(name="Сложный", description="Низкий", color="grey")
    ProjectComplexity.objects.create(name="Очень сложный", description="Низкий", color="grey")

    #LayerType
    LayerType = apps.get_model("project_catalog", "LayerType")
    LayerType.objects.create(name="Серверное приложение", description="Низкий", color="grey")
    LayerType.objects.create(name="Пользовательский интерфейс", description="Низкий", color="grey")

    #ProjectState
    ProjectState = apps.get_model("project_catalog", "ProjectState")
    ProjectState.objects.create(name="Неопределен", description="Низкий", color="grey")
    ProjectState.objects.create(name="В перспективе", description="Низкий", color="grey")
    ProjectState.objects.create(name="Проектируется", description="Низкий", color="grey")
    ProjectState.objects.create(name="Спроектирован", description="Низкий", color="grey")
    ProjectState.objects.create(name="В разработке", description="Низкий", color="grey")
    ProjectState.objects.create(name="В релизе", description="Низкий", color="grey")
    ProjectState.objects.create(name="На долгой поддержке", description="Низкий", color="grey")
    ProjectState.objects.create(name="Завершен", description="Низкий", color="grey")
    ProjectState.objects.create(name="Закрыт", description="Низкий", color="grey")
    ProjectState.objects.create(name="Отменен", description="Низкий", color="grey")
    ProjectState.objects.create(name="Планируется крупная доработка", description="Низкий", color="grey")
    ProjectState.objects.create(name="Планируется переработка", description="Низкий", color="grey")
    ProjectState.objects.create(name="Планируется обновление", description="Низкий", color="grey")
    ProjectState.objects.create(name="На переработке", description="Низкий", color="grey")
    ProjectState.objects.create(name="На доработке", description="Низкий", color="grey")
    ProjectState.objects.create(name="На обновлении", description="Низкий", color="grey")


class Migration(migrations.Migration):

    dependencies = [
        ('project_catalog', '0002_layertype_priority_projectcomplexity_projectstate_and_more'),
    ]

    operations = [migrations.RunPython(filling_manual)
    ]
