# Generated by Django 5.0.4 on 2024-04-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_catalog', '0004_stack_comment_commentsfile_historyofchange_layer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='stack',
        ),
        migrations.AddField(
            model_name='teammember',
            name='stack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='project_catalog.stack'),
            preserve_default=False,
        ),
    ]
