# Generated by Django 5.0.4 on 2024-04-15 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_catalog', '0005_remove_teammember_stack_teammember_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='project_catalog.project'),
        ),
    ]
