# Generated by Django 5.0.4 on 2024-04-29 08:34

from django.db import migrations

def filling_manual(apps, schema_editor):
    #Priority
    Priority = apps.get_model("references", "Priority")
    Priority.objects.create(name="Низкий", description="Низкий", color="grey")
    Priority.objects.create(name="Ниже среднего", description="Низкий", color="grey")
    Priority.objects.create(name="Средний", description="Низкий", color="grey")
    Priority.objects.create(name="Выше среднего", description="Низкий", color="grey")
    Priority.objects.create(name="Высокий", description="Низкий", color="grey")
    Priority.objects.create(name="Срочный", description="Низкий", color="grey")
    Priority.objects.create(name="Крайне срочный", description="Низкий", color="grey")

    #ProjectType
    ProjectType = apps.get_model("references", "ProjectType")
    ProjectType.objects.create(name="Веб приложение", description="Низкий", color="grey")
    ProjectType.objects.create(name="Система синхронизации", description="Низкий", color="grey")
    ProjectType.objects.create(name="Мобильное приложение", description="Низкий", color="grey")
    ProjectType.objects.create(name="Приложение для АРМ", description="Низкий", color="grey")
    ProjectType.objects.create(name="Информационный сайт", description="Низкий", color="grey")

    #MemberRole
    TeamMemberRole = apps.get_model("references", "MemberRole")
    TeamMemberRole.objects.create(name="Разработчик", description="Низкий", color="grey")
    TeamMemberRole.objects.create(name="Тестировщик", description="Низкий", color="grey")
    TeamMemberRole.objects.create(name="Писатель", description="Низкий", color="grey")
    TeamMemberRole.objects.create(name="Дизайнер", description="Низкий", color="grey")
    TeamMemberRole.objects.create(name="Аналитик", description="Низкий", color="grey")
    
    #Complexity
    ProjectComplexity = apps.get_model("references", "Complexity")
    ProjectComplexity.objects.create(name="Простой", description="Низкий", color="grey")
    ProjectComplexity.objects.create(name="Ниже среднего", description="Низкий", color="grey")
    ProjectComplexity.objects.create(name="Средний", description="Низкий", color="grey")
    ProjectComplexity.objects.create(name="Выше среднего", description="Низкий", color="grey")
    ProjectComplexity.objects.create(name="Сложный", description="Низкий", color="grey")
    ProjectComplexity.objects.create(name="Очень сложный", description="Низкий", color="grey")

    #LayerType
    LayerType = apps.get_model("references", "LayerType")
    LayerType.objects.create(name="Серверное приложение", description="Низкий", color="grey")
    LayerType.objects.create(name="Пользовательский интерфейс", description="Низкий", color="grey")


class Migration(migrations.Migration):

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [migrations.RunPython(filling_manual)
    ]
