# Generated by Django 5.0.4 on 2024-04-29 08:52

from django.db import migrations

def filling_manual(apps, schema_editor):
    #Status
    ProjectState = apps.get_model("statuses", "Status")
    ProjectState.objects.create(name="Неопределен", description="Низкий", color="grey")
    ProjectState.objects.create(name="В перспективе", description="Низкий", color="grey")
    ProjectState.objects.create(name="Проектируется", description="Низкий", color="grey")
    ProjectState.objects.create(name="Спроектирован", description="Низкий", color="grey")
    ProjectState.objects.create(name="В разработке", description="Низкий", color="grey")
    ProjectState.objects.create(name="В релизе", description="Низкий", color="grey")
    ProjectState.objects.create(name="На долгой поддержке", description="Низкий", color="grey")
    ProjectState.objects.create(name="Завершен", description="Низкий", color="grey")
    ProjectState.objects.create(name="Закрыт", description="Низкий", color="grey")
    ProjectState.objects.create(name="Отменен", description="Низкий", color="grey")
    ProjectState.objects.create(name="Планируется крупная доработка", description="Низкий", color="grey")
    ProjectState.objects.create(name="Планируется переработка", description="Низкий", color="grey")
    ProjectState.objects.create(name="Планируется обновление", description="Низкий", color="grey")
    ProjectState.objects.create(name="На переработке", description="Низкий", color="grey")
    ProjectState.objects.create(name="На доработке", description="Низкий", color="grey")
    ProjectState.objects.create(name="На обновлении", description="Низкий", color="grey")


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0002_initial'),
    ]

    operations = [migrations.RunPython(filling_manual)
    ]
