# Generated by Django 5.0.4 on 2024-05-03 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
        ('references', '0002_auto_20240429_1134'),
        ('teams', '0002_alter_viewer_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='member',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='member',
            name='stack',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='date_joining',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='date_termination',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_application',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='is_responsible',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='layer',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='project',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='role',
        ),
        migrations.AddField(
            model_name='member',
            name='date_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date_termination',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='is_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='is_approved',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_responsible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='layer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.layer'),
        ),
        migrations.AddField(
            model_name='member',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='references.memberrole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True, verbose_name='email addres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='first_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='worker',
            name='last_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='patronymic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='worker',
            name='stack',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='projects.stack'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_member_account', to=settings.AUTH_USER_MODEL),
        ),
    ]
