# Generated by Django 5.0.4 on 2024-05-03 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_remove_member_email_remove_member_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stackholder',
            old_name='observer',
            new_name='viewer',
        ),
        migrations.RemoveField(
            model_name='member',
            name='employee',
        ),
        migrations.AddField(
            model_name='member',
            name='worker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.worker'),
            preserve_default=False,
        ),
    ]
