# Generated by Django 5.0.4 on 2024-05-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_stackelement_name_alter_stackelement_version'),
        ('teams', '0004_rename_observer_stackholder_viewer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='viewer_projects', to='projects.project'),
        ),
    ]
