# Generated by Django 5.0.4 on 2024-05-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_stackelement_name_alter_stackelement_version'),
        ('teams', '0005_alter_viewer_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewer',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewer_projects', to='projects.project'),
        ),
    ]
