# Generated by Django 5.0.4 on 2024-05-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_alter_viewer_project'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
