# Generated by Django 5.0.4 on 2024-06-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_user_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='is_approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
