# Generated by Django 5.0.4 on 2024-06-10 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_member_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
