# Generated by Django 5.0.4 on 2024-04-28 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('domain', models.CharField(max_length=100, unique=True)),
                ('version', models.CharField(help_text='Указывается при помощи 2 чисел разделенных запятой', max_length=10)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('project_goal', models.CharField(blank=True, max_length=2000)),
                ('project_tasks', models.TextField(blank=True)),
                ('project_functionality', models.TextField(blank=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('file_type', models.CharField(choices=[('t_entry', 'Введение'), ('t_ps', 'ТЗ'), ('t_fun_desc', 'Функциональное описание'), ('t_scheme', 'Схема'), ('t_other', 'Другое')], max_length=20)),
                ('file', models.FileField(upload_to='uploads/ProjectDocument')),
                ('file_ver', models.CharField(help_text='Указывается при помощи 2 чисел разделенных запятой', max_length=10)),
                ('is_visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('quarter', models.CharField(choices=[('q1', 'Q1'), ('q2', 'Q2'), ('q3', 'Q3'), ('q4', 'Q4')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='StackElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('introduced', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('link_to_project_in_git', models.URLField(blank=True, null=True)),
                ('link_to_project_in_ser_reg', models.URLField(blank=True, null=True)),
                ('expected_testbed_start_date', models.DateField(blank=True, null=True)),
                ('complexity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.complexity')),
                ('layer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.layertype')),
            ],
        ),
    ]
