# Generated by Django 5.0.4 on 2024-04-28 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('references', '0001_initial'),
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.status'),
        ),
        migrations.AddField(
            model_name='project',
            name='complexity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.complexity'),
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.priority'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='references.projecttype'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='statuses.status'),
        ),
        migrations.AddField(
            model_name='layer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='prev',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.projectdocument'),
        ),
        migrations.AddField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='quarter',
            constraint=models.UniqueConstraint(fields=('year', 'quarter'), name='quarter_constr'),
        ),
        migrations.AddField(
            model_name='project',
            name='quarter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.quarter'),
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.stack'),
        ),
        migrations.AddField(
            model_name='layer',
            name='stack',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.stack'),
        ),
        migrations.AddField(
            model_name='stackelement',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.stackelement'),
        ),
        migrations.AddField(
            model_name='stack',
            name='elements',
            field=models.ManyToManyField(to='projects.stackelement'),
        ),
    ]
