# Generated by Django 5.0.4 on 2024-05-03 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layer',
            old_name='state',
            new_name='status',
        ),
    ]
