# Generated by Django 5.0.4 on 2024-05-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_state_layer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stack',
            name='elements',
            field=models.ManyToManyField(related_name='elements', to='projects.stackelement'),
        ),
    ]
