# Generated by Django 5.0.4 on 2024-05-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_stack_elements'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stackelement',
            unique_together={('name', 'version')},
        ),
    ]
