# Generated by Django 5.0.4 on 2024-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_stackelement_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackelement',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stackelement',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
