# Generated by Django 5.0.4 on 2024-05-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_stackelement_name_alter_stackelement_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarter',
            name='quarter',
            field=models.CharField(choices=[('квартал 1', 'Q1'), ('квартал 2', 'Q2'), ('квартал 2', 'Q3'), ('квартал 3', 'Q4')], max_length=9),
        ),
    ]
